### ISSUE TITLE
request an example to illustrate the "transparent regulatory" 

### ISSUE THREAD

**Issue by keybatman** [WiSaGaN/ctp-rs#10]
Is it possible to add an example for `api-trader` to illustrate that, how to comply the "transparent regulatory" in `ctp-rs`, please?
Thanks!

**Comment by WiSaGaN** [comment]
You'll need to pass conformance tests required by futures brokerage company, and get an app id and auth code. And then use that app id and auth code to login to prod system. Please consulte with your brokerage company to get details.

**Comment by KeyBat** [comment]
Yes, that is important. Thank you for the kind remind.

Also, I have noticed that only the traditional way, ie, [req_user_login](https://github.com/WiSaGaN/ctp-rs/blob/master/ctp-trader/examples/api-trader.rs#L160), appeared in `ctp-trader/examples/api-trader.rs`.

Can you please add an example illustrating the `req_authenticate` way to `api-trader` examples?
The latter seems much more complicated than the traditional way.

**Comment by keybatman** [comment]
Yes, that is it. Thank you for the kind remind.
