### ISSUE TITLE
request an example to illustrate the using the whole project

### ISSUE THREAD

**Issue by keybatman** [WiSaGaN/ctp-rs#11]
Hi @WiSaGaN , can you please provide an example, e.g., a very simple trading strategy,
for using `ctp-rs` as a whole?

Thanks a lot!

Update:
Although I have managed to make myApp works, I still believe that, an illustrating example would be very helpful for new comers.

**Comment by WiSaGaN** [comment]
There are examples under `ctp-trader/examples` and `ctp-md/examples`. Strategies though are out of scope for this project.

**Comment by keybatman** [comment]
Thanks for the reply.
