### ISSUE TITLE
How to call trader_api in traderSPI?

### ISSUE THREAD

**Issue by EGBAR** [WiSaGaN/ctp-rs#14]
Hi, 

Thanks for your hard working! Finally we have a rust-ctp framework. I could run the demo well and learned a lot.
I have a problem when I try to call "trader_api" in SPI. For example, call **reqAuthenticate()** and **reqUserLogin()** when **onFrontConnected** callback. Or try to cancel orders inside **on_rsp_order_insert()**

I tried to pass trader_api into SPI's structure but it seems not work. 

```
struct Spi<'a>{
    trader_api: &'a ctp_trader::TraderApi,
}

impl TraderSpi for Spi {
    //On trading front end connected
    fn on_front_connected(&mut self) {
        println!("on_front_connected");
    }
}
...
let mut trader_api = TraderApi::new(std::ffi::CString::new("").unwrap());
trader_api.register_spi(Box::new(Spi{trader_api: &trader_api}));
```
with error
`main.rs(12, 6): *mut std::ffi::c_void cannot be shared between threads `

Do you have any good suggestions? 
Thanks you!

**Comment by WiSaGaN** [comment]
Normally you shouldn't do this, but should instead handle in spi either
* use a channel (there is one `channel` feature wrapping `crossbeam-channel`) to send back the event
* update a synchronised data structure that the main thread (the thread api object lives in) that can access

In the future, we may make api object clonable and sendable to different threads. In this case, we can wrap one of this api object in the spi callback.

**Comment by EGBAR** [comment]
Hi,
Would you mind write an example with the channel feature and show how to communicate between two threads?
I still couldn't figure this out after learning basic rust tutorial.

Thanks!

One use case is:
I created a redis client in "main" thread. I want to catch returned data from spi and send them into redis server.

**Comment by EGBAR** [comment]
Solved.

Need to enable 'channel' feature in new crate's configure file.

Cargo.toml
`[dependencies.ctp-trader]
path = "../ctp-rs/ctp-trader"
features = ["channel"]`

main.rs
```
let (tx, rx) = crossbeam_channel::unbounded();
 trader_api.register_spi(Box::new(ChannelTraderSpi::new(tx)));
...
for received in rx{
        println!("channel received: {:?}", received);
    }
```

Thanks!
