### ISSUE TITLE
subscribe_market_data成功后，如何触发on_rsp_sub_market_data

### ISSUE THREAD

**Issue by martinx** [WiSaGaN/ctp-rs#15]
请教下，订阅成功后，没有推送行情数据是因为？

```rust
let (tx, rx) = crossbeam_channel::unbounded();
md_api.register_spi(Box::new(ChannelMdSpi::new(tx)));
...

let instrument_ids = vec!(CString::new("FU2005").unwrap(), CString::new("IC8888").unwrap());
match md_api.subscribe_market_data(&instrument_ids.clone()) {
    Ok(()) => println!("subscribe_market_data ok"),
    Err(err) => println!("subscribe_market_data err: {:?}", err),
};

for received in rx {
    println!("received: {:?}", received);
}
```

登录成功后，只能从 channel 中收到 行情订阅响应，按下面的流程图，订阅成功后应该会自动推送行情

![image](https://assets-3.ubairn.com/WechatIMG2195.jpeg)

但是后面就一直处于等待状态

```
subscribe_market_data ok

received: (SubMarketData(MdSpiOnRspSubMarketData { specific_instrument: Some(CThostFtdcSpecificInstrumentField { InstrumentID: "FU2005" }), result: Ok(()), request_id: 0, is_last: false }), SystemTime { tv_sec: 1585709336, tv_nsec: 876154074 })

received: (SubMarketData(MdSpiOnRspSubMarketData { specific_instrument: Some(CThostFtdcSpecificInstrumentField { InstrumentID: "IC8888" }), result: Ok(()), request_id: 0, is_last: true }), SystemTime { tv_sec: 1585709336, tv_nsec: 876156269 })

// 一直等待，没有任何输出信息
```

多谢了。

**Comment by martinx** [comment]
按文档应该在订阅成功后，先触发 on_rsp_sub_market_data，然后有数据触发 on_rtn_depth_market_data 这个event。

在执行过程中，订阅成功了，on_rsp_sub_market_data也触发了，但是最后一个on_rtn_depth_market_data 一直没有触发，不知道哪里理解错了。

**Comment by WiSaGaN** [comment]
可以检查一下数据源是否有数据
* 是否交易时间
* 合约是否是活跃合约

**Comment by martinx** [comment]
多谢帮忙解答，也谢谢提供这么棒的项目 👍 

刚发现我发现一个很白的问题，合约字母我大写了，刚给为小写收到最后一条价格，等明天开票看下是否一切正常。

> channel received: (DepthMarketData(MdSpiOnRtnDepthMarketData { depth_market_data: CThostFtdcDepthMarketDataField { TradingDay: "20200402", InstrumentID: "l2009", ExchangeID: "", ExchangeInstID: "", LastPrice: Some(5805.0), PreSettlementPrice: Some(5515.0), PreClosePrice: Some(5565.0), PreOpenInterest: 325023.0, OpenPrice: Some(5575.0), HighestPrice: Some(5845.0), LowestPrice: Some(5555.0), Volume: 597898, Turnover: 17032718925.0, OpenInterest: 322491.0, ClosePrice: Some(5805.0), SettlementPrice: Some(5695.0), UpperLimitPrice: Some(5845.0), LowerLimitPrice: Some(5185.0), PreDelta: Some(0.0), CurrDelta: Some(0.0), UpdateTime: "15:01:28", UpdateMillisec: 685, BidPrice1: Some(5800.0), BidVolume1: 457, AskPrice1: Some(5805.0), AskVolume1: 96, AveragePrice: Some(28487.666667224174), ActionDay: "20200402" } }), SystemTime { tv_sec: 1585811900, tv_nsec: 742365960 })
