### ISSUE TITLE
是否有兴趣做成网关 ？ 

### ISSUE THREAD

**Issue by somewheve** [WiSaGaN/ctp-rs#16]
描述为一个类似快期OTG的网关 ，但是想通过APT 或者pacman进行安装

**Comment by somewheve** [comment]
我计划是通过actix提供ws推送信息， 通过Actor自主管理开盘和收盘。  到时候在linux上部署好， c++对于我而言太难了  用rust现有的生态会比较简单 。 如果你有兴趣 我们可以共同开发

**Comment by WiSaGaN** [comment]
我没有计划。你可以自行fork并开发。

**Comment by somewheve** [comment]
好吧
