### ISSUE TITLE
How does the `#[link_name = ]` thing work?

### ISSUE THREAD

**Issue by Notmeor** [WiSaGaN/ctp-rs#8]
Such as 
```
#[link_name = "_ZN14CFtdcMdApiImpl13GetTradingDayEv"]
fn CFtdcMdApiImplGetTradingDay(api: *mut c_void) -> *const c_char;
```
Why the name "_ZN14CFtdcMdApiImpl13GetTradingDayEv", any guidance?

**Comment by WiSaGaN** [comment]
This is the attribute to specify the actual symbol in the shared library: https://doc.rust-lang.org/reference/items/external-blocks.html#the-link_name-attribute

In this case, we are using the mangled C++ symbol in the linux 64 so.

**Comment by Notmeor** [comment]
```
In this case, we are using the mangled C++ symbol in the linux 64 so.
```
How is the mangled C++ symbol generated?

**Comment by WiSaGaN** [comment]
You can check out here: https://en.wikipedia.org/wiki/Name_mangling#C++
